services:
    vitemail-bot-node:
        container_name: vitemail-bot-node
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - TZ=Asia/Jakarta
        env_file:
            - .env
        ports:
            - '127.0.0.1:3005:3000'
        volumes:
            - ./data:/app/data
            - ./log:/app/logs
